name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '**.py'
      - 'setup.py'
  pull_request:
    paths:
        - '.github/workflows/**'
        - '**.py'
        - 'setup.py'
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements-test.txt

      - name: Run Tests
        run: |
          pytest
